using UnityEngine;
using VDPackages.FMODUtilityPackage.Core;

namespace VDPackages.FMODUtilityPackage.Enums
{
	// ReSharper disable InconsistentNaming
	/// <summary>
	/// All FMOD events, these are automatically generated by the <see cref="AudioManager"/>
	/// </summary>
	public enum AudioEvent // Automatically generated from FMOD events, do not edit! (Open the AudioManager inspector or use the "FMOD/Import Events" menu to regenerate)
	{
		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Cassette/Pickup_FromCase
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Cassette/Pickup_FromCase")]
		StudentLevel_Ingredients_Cassette_Pickup_FromCase,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedBeans/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedBeans/Moving")]
		StudentLevel_Ingredients_CannedBeans_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Pasta/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Pasta/Moving")]
		StudentLevel_Ingredients_Pasta_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Shelf/Close
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Shelf/Close")]
		StudentLevel_Interactions_Shelf_Close,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/TapeDeck/Open
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/TapeDeck/Open")]
		StudentLevel_Interactions_TapeDeck_Open,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedBeans/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedBeans/Drop")]
		StudentLevel_Ingredients_CannedBeans_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/EggCarton/Open
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/EggCarton/Open")]
		StudentLevel_Interactions_EggCarton_Open,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Sponge/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Sponge/Moving")]
		StudentLevel_Ingredients_Sponge_Moving,

		/// <FMODEventPath>
		/// event:/MainMenu/Pen/Pen_Pickup
		/// </FMODEventPath>
		[InspectorName("MainMenu/Pen/Pen_Pickup")]
		MainMenu_Pen_Pen_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/TapeDeck/Insert_Cassette
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/TapeDeck/Insert_Cassette")]
		StudentLevel_Interactions_TapeDeck_Insert_Cassette,

		/// <FMODEventPath>
		/// event:/MainMenu/Pen/Pen_Drop
		/// </FMODEventPath>
		[InspectorName("MainMenu/Pen/Pen_Drop")]
		MainMenu_Pen_Pen_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Cassette/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Cassette/Drop")]
		StudentLevel_Ingredients_Cassette_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedBeans/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedBeans/Pickup")]
		StudentLevel_Ingredients_CannedBeans_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Pasta/DirectionChange
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Pasta/DirectionChange")]
		StudentLevel_Ingredients_Pasta_DirectionChange,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Place_SecondMug
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Place_SecondMug")]
		StudentLevel_Interactions_Dishes_Place_SecondMug,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Cassette/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Cassette/Pickup")]
		StudentLevel_Ingredients_Cassette_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Key/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Key/Moving")]
		StudentLevel_Ingredients_Key_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Milk/DirectionChange
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Milk/DirectionChange")]
		StudentLevel_Ingredients_Milk_DirectionChange,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Toaster/Activate
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Toaster/Activate")]
		StudentLevel_Interactions_Toaster_Activate,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Key/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Key/Drop")]
		StudentLevel_Ingredients_Key_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Milk/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Milk/Moving")]
		StudentLevel_Ingredients_Milk_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Place_FirstPlate
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Place_FirstPlate")]
		StudentLevel_Interactions_Dishes_Place_FirstPlate,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedBeans/DirectionChange
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedBeans/DirectionChange")]
		StudentLevel_Ingredients_CannedBeans_DirectionChange,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Key/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Key/Pickup")]
		StudentLevel_Ingredients_Key_Pickup,

		/// <FMODEventPath>
		/// event:/MainMenu/Pen/Pen_Down
		/// </FMODEventPath>
		[InspectorName("MainMenu/Pen/Pen_Down")]
		MainMenu_Pen_Pen_Down,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Pan/Cooking
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Pan/Cooking")]
		StudentLevel_Interactions_Pan_Cooking,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Soap/Bubbles
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Soap/Bubbles")]
		StudentLevel_Interactions_Soap_Bubbles,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Place_SecondPlate
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Place_SecondPlate")]
		StudentLevel_Interactions_Dishes_Place_SecondPlate,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Lock/Locked
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Lock/Locked")]
		StudentLevel_Interactions_Lock_Locked,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/EggCarton/Close
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/EggCarton/Close")]
		StudentLevel_Interactions_EggCarton_Close,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Pasta/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Pasta/Drop")]
		StudentLevel_Ingredients_Pasta_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Toaster/Eject
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Toaster/Eject")]
		StudentLevel_Interactions_Toaster_Eject,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/TapeDeck/TakeOut_Cassette
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/TapeDeck/TakeOut_Cassette")]
		StudentLevel_Interactions_TapeDeck_TakeOut_Cassette,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Tap/Water_Rising
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Tap/Water_Rising")]
		StudentLevel_Interactions_Tap_Water_Rising,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Tap/Running
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Tap/Running")]
		StudentLevel_Interactions_Tap_Running,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Sponge/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Sponge/Drop")]
		StudentLevel_Ingredients_Sponge_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/PeanutButter/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/PeanutButter/Drop")]
		StudentLevel_Ingredients_PeanutButter_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Cassette/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Cassette/Moving")]
		StudentLevel_Ingredients_Cassette_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Toaster/Toasting
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Toaster/Toasting")]
		StudentLevel_Interactions_Toaster_Toasting,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Place_Mug
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Place_Mug")]
		StudentLevel_Interactions_Dishes_Place_Mug,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Milk/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Milk/Drop")]
		StudentLevel_Ingredients_Milk_Drop,

		/// <FMODEventPath>
		/// event:/MainMenu/Pen/Pen_Drawing
		/// </FMODEventPath>
		[InspectorName("MainMenu/Pen/Pen_Drawing")]
		MainMenu_Pen_Pen_Drawing,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Sponge/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Sponge/Pickup")]
		StudentLevel_Ingredients_Sponge_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Pasta/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Pasta/Pickup")]
		StudentLevel_Ingredients_Pasta_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Plant/Touch
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Plant/Touch")]
		StudentLevel_Interactions_Plant_Touch,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Cassette/DirectionChange
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Cassette/DirectionChange")]
		StudentLevel_Ingredients_Cassette_DirectionChange,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Lock/Unlocking
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Lock/Unlocking")]
		StudentLevel_Interactions_Lock_Unlocking,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Toaster/Slide
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Toaster/Slide")]
		StudentLevel_Interactions_Toaster_Slide,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Mugs/Collision
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Mugs/Collision")]
		StudentLevel_Interactions_Mugs_Collision,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Rattle
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Rattle")]
		StudentLevel_Interactions_Dishes_Rattle,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/PeanutButter/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/PeanutButter/Pickup")]
		StudentLevel_Ingredients_PeanutButter_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/TapeDeck/Close
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/TapeDeck/Close")]
		StudentLevel_Interactions_TapeDeck_Close,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Shelf/Open
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Shelf/Open")]
		StudentLevel_Interactions_Shelf_Open,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Milk/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Milk/Pickup")]
		StudentLevel_Ingredients_Milk_Pickup,

		/// <FMODEventPath>
		/// event:/UI/Book/Switch_Tab
		/// </FMODEventPath>
		[InspectorName("UI/Book/Switch_Tab")]
		UI_Book_Switch_Tab,

		/// <FMODEventPath>
		/// event:/UI/Book/Close
		/// </FMODEventPath>
		[InspectorName("UI/Book/Close")]
		UI_Book_Close,

		/// <FMODEventPath>
		/// event:/UI/PauseMenu/Close
		/// </FMODEventPath>
		[InspectorName("UI/PauseMenu/Close")]
		UI_PauseMenu_Close,

		/// <FMODEventPath>
		/// event:/UI/Recipes/Bad_Recipe
		/// </FMODEventPath>
		[InspectorName("UI/Recipes/Bad_Recipe")]
		UI_Recipes_Bad_Recipe,

		/// <FMODEventPath>
		/// event:/UI/PauseMenu/Open
		/// </FMODEventPath>
		[InspectorName("UI/PauseMenu/Open")]
		UI_PauseMenu_Open,

		/// <FMODEventPath>
		/// event:/UI/Mouse_Down
		/// </FMODEventPath>
		[InspectorName("UI/Mouse_Down")]
		UI_Mouse_Down,

		/// <FMODEventPath>
		/// event:/UI/Book/Hover_Tab
		/// </FMODEventPath>
		[InspectorName("UI/Book/Hover_Tab")]
		UI_Book_Hover_Tab,

		/// <FMODEventPath>
		/// event:/UI/Book/Open
		/// </FMODEventPath>
		[InspectorName("UI/Book/Open")]
		UI_Book_Open,

		/// <FMODEventPath>
		/// event:/UI/Recipes/Good_Recipe
		/// </FMODEventPath>
		[InspectorName("UI/Recipes/Good_Recipe")]
		UI_Recipes_Good_Recipe,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ambience/StudentLevel_Ambience
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ambience/StudentLevel_Ambience")]
		StudentLevel_Ambience_StudentLevel_Ambience,

		/// <FMODEventPath>
		/// snapshot:/PauseMenu
		/// </FMODEventPath>
		[InspectorName("t:/PauseMenu")]
		PauseMenu,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Pan/Water_Splash_Big
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Pan/Water_Splash_Big")]
		StudentLevel_Interactions_Pan_Water_Splash_Big,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Pan/Water_Splash_Medium
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Pan/Water_Splash_Medium")]
		StudentLevel_Interactions_Pan_Water_Splash_Medium,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Pasta/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Pasta/Impact")]
		StudentLevel_Ingredients_Pasta_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Cassette/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Cassette/Impact")]
		StudentLevel_Ingredients_Cassette_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Key/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Key/Impact")]
		StudentLevel_Ingredients_Key_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Pan/Closing
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Pan/Closing")]
		StudentLevel_Interactions_Pan_Closing,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Sponge/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Sponge/Impact")]
		StudentLevel_Ingredients_Sponge_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/PeanutButter/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/PeanutButter/Impact")]
		StudentLevel_Ingredients_PeanutButter_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedBeans/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedBeans/Impact")]
		StudentLevel_Ingredients_CannedBeans_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Milk/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Milk/Impact")]
		StudentLevel_Ingredients_Milk_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Pan/Water_Splash_Small
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Pan/Water_Splash_Small")]
		StudentLevel_Interactions_Pan_Water_Splash_Small,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Place_FirstBowl
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Place_FirstBowl")]
		StudentLevel_Interactions_Dishes_Place_FirstBowl,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/MysteryJar/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/MysteryJar/Pickup")]
		StudentLevel_Ingredients_MysteryJar_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Egg/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Egg/Drop")]
		StudentLevel_Ingredients_Egg_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/ProteinPowder/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/ProteinPowder/Moving")]
		StudentLevel_Ingredients_ProteinPowder_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Cleaning
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Cleaning")]
		StudentLevel_Interactions_Dishes_Cleaning,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Tap/Sink_Emptying
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Tap/Sink_Emptying")]
		StudentLevel_Interactions_Tap_Sink_Emptying,

		/// <FMODEventPath>
		/// event:/MainMenu/Noodles/HoverDown
		/// </FMODEventPath>
		[InspectorName("MainMenu/Noodles/HoverDown")]
		MainMenu_Noodles_HoverDown,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Potato/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Potato/Moving")]
		StudentLevel_Ingredients_Potato_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Knife/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Knife/Drop")]
		StudentLevel_Ingredients_Knife_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Place_MokaPot
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Place_MokaPot")]
		StudentLevel_Interactions_Dishes_Place_MokaPot,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/ProteinPowder/DirectionChange
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/ProteinPowder/DirectionChange")]
		StudentLevel_Ingredients_ProteinPowder_DirectionChange,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Potato/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Potato/Pickup")]
		StudentLevel_Ingredients_Potato_Pickup,

		/// <FMODEventPath>
		/// event:/MainMenu/Key/HoverDown
		/// </FMODEventPath>
		[InspectorName("MainMenu/Key/HoverDown")]
		MainMenu_Key_HoverDown,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Place_SecondBowl
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Place_SecondBowl")]
		StudentLevel_Interactions_Dishes_Place_SecondBowl,

		/// <FMODEventPath>
		/// event:/MainMenu/Letters/Pickup
		/// </FMODEventPath>
		[InspectorName("MainMenu/Letters/Pickup")]
		MainMenu_Letters_Pickup,

		/// <FMODEventPath>
		/// event:/MainMenu/Cassette/HoverDown
		/// </FMODEventPath>
		[InspectorName("MainMenu/Cassette/HoverDown")]
		MainMenu_Cassette_HoverDown,

		/// <FMODEventPath>
		/// event:/MainMenu/Key/HoverUp
		/// </FMODEventPath>
		[InspectorName("MainMenu/Key/HoverUp")]
		MainMenu_Key_HoverUp,

		/// <FMODEventPath>
		/// event:/MainMenu/Polaroid/HoverDown
		/// </FMODEventPath>
		[InspectorName("MainMenu/Polaroid/HoverDown")]
		MainMenu_Polaroid_HoverDown,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/WhiteBread/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/WhiteBread/Moving")]
		StudentLevel_Ingredients_WhiteBread_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Potato/PotatoSack_Closed
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Potato/PotatoSack_Closed")]
		StudentLevel_Ingredients_Potato_PotatoSack_Closed,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Egg/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Egg/Impact")]
		StudentLevel_Ingredients_Egg_Impact,

		/// <FMODEventPath>
		/// event:/MainMenu/Polaroid/HoverUp
		/// </FMODEventPath>
		[InspectorName("MainMenu/Polaroid/HoverUp")]
		MainMenu_Polaroid_HoverUp,

		/// <FMODEventPath>
		/// event:/MainMenu/Cassette/HoverUp
		/// </FMODEventPath>
		[InspectorName("MainMenu/Cassette/HoverUp")]
		MainMenu_Cassette_HoverUp,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Tap/Water_Sinking
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Tap/Water_Sinking")]
		StudentLevel_Interactions_Tap_Water_Sinking,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Knife/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Knife/Impact")]
		StudentLevel_Ingredients_Knife_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/MysteryJar/DirectionChange
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/MysteryJar/DirectionChange")]
		StudentLevel_Ingredients_MysteryJar_DirectionChange,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/WhiteBread/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/WhiteBread/Pickup")]
		StudentLevel_Ingredients_WhiteBread_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Tap/Sink_Overflowing
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Tap/Sink_Overflowing")]
		StudentLevel_Interactions_Tap_Sink_Overflowing,

		/// <FMODEventPath>
		/// event:/MainMenu/Letters/Drop
		/// </FMODEventPath>
		[InspectorName("MainMenu/Letters/Drop")]
		MainMenu_Letters_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/WhiteBread/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/WhiteBread/Impact")]
		StudentLevel_Ingredients_WhiteBread_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/ProteinPowder/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/ProteinPowder/Drop")]
		StudentLevel_Ingredients_ProteinPowder_Drop,

		/// <FMODEventPath>
		/// event:/MainMenu/Pen/Pen_HoverDown
		/// </FMODEventPath>
		[InspectorName("MainMenu/Pen/Pen_HoverDown")]
		MainMenu_Pen_Pen_HoverDown,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Egg/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Egg/Moving")]
		StudentLevel_Ingredients_Egg_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/MysteryJar/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/MysteryJar/Moving")]
		StudentLevel_Ingredients_MysteryJar_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Egg/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Egg/Pickup")]
		StudentLevel_Ingredients_Egg_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Knife/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Knife/Moving")]
		StudentLevel_Ingredients_Knife_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/PaperLetter/Open
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/PaperLetter/Open")]
		StudentLevel_Interactions_PaperLetter_Open,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Potato/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Potato/Impact")]
		StudentLevel_Ingredients_Potato_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Tap/TurnOff
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Tap/TurnOff")]
		StudentLevel_Interactions_Tap_TurnOff,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Place_ThirdBowl
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Place_ThirdBowl")]
		StudentLevel_Interactions_Dishes_Place_ThirdBowl,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/WhiteBread/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/WhiteBread/Drop")]
		StudentLevel_Ingredients_WhiteBread_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Tap/Sink_Filling
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Tap/Sink_Filling")]
		StudentLevel_Interactions_Tap_Sink_Filling,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/ProteinPowder/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/ProteinPowder/Impact")]
		StudentLevel_Ingredients_ProteinPowder_Impact,

		/// <FMODEventPath>
		/// event:/MainMenu/Pen/Pen_HoverUp
		/// </FMODEventPath>
		[InspectorName("MainMenu/Pen/Pen_HoverUp")]
		MainMenu_Pen_Pen_HoverUp,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Tap/TurnOn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Tap/TurnOn")]
		StudentLevel_Interactions_Tap_TurnOn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/MysteryJar/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/MysteryJar/Impact")]
		StudentLevel_Ingredients_MysteryJar_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/TapeDeck/Music
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/TapeDeck/Music")]
		StudentLevel_Interactions_TapeDeck_Music,

		/// <FMODEventPath>
		/// event:/MainMenu/Noodles/HoverUp
		/// </FMODEventPath>
		[InspectorName("MainMenu/Noodles/HoverUp")]
		MainMenu_Noodles_HoverUp,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Pan/Spin_StoveDials
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Pan/Spin_StoveDials")]
		StudentLevel_Interactions_Pan_Spin_StoveDials,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/CartonBox/Rattle
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/CartonBox/Rattle")]
		StudentLevel_Interactions_CartonBox_Rattle,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/MysteryJar/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/MysteryJar/Drop")]
		StudentLevel_Ingredients_MysteryJar_Drop,

		/// <FMODEventPath>
		/// event:/MainMenu/Letters/Moving
		/// </FMODEventPath>
		[InspectorName("MainMenu/Letters/Moving")]
		MainMenu_Letters_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/ProteinPowder/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/ProteinPowder/Pickup")]
		StudentLevel_Ingredients_ProteinPowder_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Cleaning_Finished
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Cleaning_Finished")]
		StudentLevel_Interactions_Dishes_Cleaning_Finished,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/WhiteBread/Pickup_FromBag
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/WhiteBread/Pickup_FromBag")]
		StudentLevel_Ingredients_WhiteBread_Pickup_FromBag,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/PaperLetter/Close
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/PaperLetter/Close")]
		StudentLevel_Interactions_PaperLetter_Close,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Knife/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Knife/Pickup")]
		StudentLevel_Ingredients_Knife_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Potato/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Potato/Drop")]
		StudentLevel_Ingredients_Potato_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Soap/Bubble_Pop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Soap/Bubble_Pop")]
		StudentLevel_Interactions_Soap_Bubble_Pop,

		/// <FMODEventPath>
		/// event:/UI/Book/SelectDish
		/// </FMODEventPath>
		[InspectorName("UI/Book/SelectDish")]
		UI_Book_SelectDish,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/TapeDeck/Antenna
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/TapeDeck/Antenna")]
		StudentLevel_Interactions_TapeDeck_Antenna,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Potato/PotatoSack_Cut
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Potato/PotatoSack_Cut")]
		StudentLevel_Ingredients_Potato_PotatoSack_Cut,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Place_SmallKnife
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Place_SmallKnife")]
		StudentLevel_Interactions_Dishes_Place_SmallKnife,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Egg/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Egg/Respawn")]
		StudentLevel_Ingredients_Egg_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedBeans/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedBeans/Respawn")]
		StudentLevel_Ingredients_CannedBeans_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Milk/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Milk/Respawn")]
		StudentLevel_Ingredients_Milk_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/MysteryJar/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/MysteryJar/Respawn")]
		StudentLevel_Ingredients_MysteryJar_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Respawn")]
		StudentLevel_Ingredients_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/MysteryJar/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/MysteryJar/Respawn_Land")]
		StudentLevel_Ingredients_MysteryJar_Respawn_Land,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Tap/Water_Splash
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Tap/Water_Splash")]
		StudentLevel_Interactions_Tap_Water_Splash,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Cleaning_Bubble_Spawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Cleaning_Bubble_Spawn")]
		StudentLevel_Interactions_Dishes_Cleaning_Bubble_Spawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Cassette/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Cassette/Respawn")]
		StudentLevel_Ingredients_Cassette_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Pasta/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Pasta/Respawn_Land")]
		StudentLevel_Ingredients_Pasta_Respawn_Land,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Pasta/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Pasta/Respawn")]
		StudentLevel_Ingredients_Pasta_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Key/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Key/Respawn")]
		StudentLevel_Ingredients_Key_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Dishes/Cleaning_Bubble_Pop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Dishes/Cleaning_Bubble_Pop")]
		StudentLevel_Interactions_Dishes_Cleaning_Bubble_Pop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Knife/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Knife/Respawn")]
		StudentLevel_Ingredients_Knife_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/ProteinPowder/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/ProteinPowder/Respawn")]
		StudentLevel_Ingredients_ProteinPowder_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Coffee/Place_MokaPot
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Coffee/Place_MokaPot")]
		StudentLevel_Interactions_Coffee_Place_MokaPot,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Pan/Turn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Pan/Turn")]
		StudentLevel_Interactions_Pan_Turn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/CartonBox/Rattle_Closed
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/CartonBox/Rattle_Closed")]
		StudentLevel_Interactions_CartonBox_Rattle_Closed,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Coffee/Cooking_MokaPot
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Coffee/Cooking_MokaPot")]
		StudentLevel_Interactions_Coffee_Cooking_MokaPot,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedBeans/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedBeans/Respawn_Land")]
		StudentLevel_Ingredients_CannedBeans_Respawn_Land,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Milk/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Milk/Respawn_Land")]
		StudentLevel_Ingredients_Milk_Respawn_Land,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/ProteinPowder/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/ProteinPowder/Respawn_Land")]
		StudentLevel_Ingredients_ProteinPowder_Respawn_Land,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Sponge/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Sponge/Respawn")]
		StudentLevel_Ingredients_Sponge_Respawn,

		/// <FMODEventPath>
		/// event:/UI/Hover_Circle
		/// </FMODEventPath>
		[InspectorName("UI/Hover_Circle")]
		UI_Hover_Circle,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/TapeDeck/Button_Down
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/TapeDeck/Button_Down")]
		StudentLevel_Interactions_TapeDeck_Button_Down,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/TapeDeck/Button_Up
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/TapeDeck/Button_Up")]
		StudentLevel_Interactions_TapeDeck_Button_Up,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Underwater/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Underwater/Drop")]
		StudentLevel_Ingredients_Underwater_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Underwater/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Underwater/Pickup")]
		StudentLevel_Ingredients_Underwater_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/PeanutButter/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/PeanutButter/Respawn")]
		StudentLevel_Ingredients_PeanutButter_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Underwater/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Underwater/Moving")]
		StudentLevel_Ingredients_Underwater_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/PeanutButter/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/PeanutButter/Respawn_Land")]
		StudentLevel_Ingredients_PeanutButter_Respawn_Land,

		/// <FMODEventPath>
		/// event:/UI/Hover_Underline
		/// </FMODEventPath>
		[InspectorName("UI/Hover_Underline")]
		UI_Hover_Underline,

		/// <FMODEventPath>
		/// event:/UI/Book/HoverDish
		/// </FMODEventPath>
		[InspectorName("UI/Book/HoverDish")]
		UI_Book_HoverDish,

		/// <FMODEventPath>
		/// event:/UI/Hover
		/// </FMODEventPath>
		[InspectorName("UI/Hover")]
		UI_Hover,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Banana/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Banana/Moving")]
		StudentLevel_Ingredients_Banana_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Basil/Grow_Finished
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Basil/Grow_Finished")]
		StudentLevel_Ingredients_Basil_Grow_Finished,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Basil/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Basil/Pickup")]
		StudentLevel_Ingredients_Basil_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Tile/Click
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Tile/Click")]
		StudentLevel_Interactions_Tile_Click,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Jam/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Jam/Respawn_Land")]
		StudentLevel_Ingredients_Jam_Respawn_Land,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Ramen/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Ramen/Pickup")]
		StudentLevel_Ingredients_Ramen_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Ramen/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Ramen/Respawn_Land")]
		StudentLevel_Ingredients_Ramen_Respawn_Land,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Pesto/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Pesto/Respawn_Land")]
		StudentLevel_Ingredients_Pesto_Respawn_Land,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Basil/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Basil/Impact")]
		StudentLevel_Ingredients_Basil_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Jam/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Jam/Pickup")]
		StudentLevel_Ingredients_Jam_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/BigMysteryJar/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/BigMysteryJar/Impact")]
		StudentLevel_Ingredients_BigMysteryJar_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedTomatoes/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedTomatoes/Drop")]
		StudentLevel_Ingredients_CannedTomatoes_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Basil/Touch
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Basil/Touch")]
		StudentLevel_Ingredients_Basil_Touch,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/BigMysteryJar/DirectionChange
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/BigMysteryJar/DirectionChange")]
		StudentLevel_Ingredients_BigMysteryJar_DirectionChange,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Banana/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Banana/Pickup")]
		StudentLevel_Ingredients_Banana_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedTomatoes/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedTomatoes/Respawn_Land")]
		StudentLevel_Ingredients_CannedTomatoes_Respawn_Land,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Ramen/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Ramen/Impact")]
		StudentLevel_Ingredients_Ramen_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedTomatoes/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedTomatoes/Impact")]
		StudentLevel_Ingredients_CannedTomatoes_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Jam/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Jam/Respawn")]
		StudentLevel_Ingredients_Jam_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/BigMysteryJar/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/BigMysteryJar/Moving")]
		StudentLevel_Ingredients_BigMysteryJar_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Ramen/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Ramen/Moving")]
		StudentLevel_Ingredients_Ramen_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Ramen/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Ramen/Drop")]
		StudentLevel_Ingredients_Ramen_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Cheese/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Cheese/Drop")]
		StudentLevel_Ingredients_Cheese_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Ramen/DirectionChange
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Ramen/DirectionChange")]
		StudentLevel_Ingredients_Ramen_DirectionChange,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Banana/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Banana/Impact")]
		StudentLevel_Ingredients_Banana_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Pesto/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Pesto/Drop")]
		StudentLevel_Ingredients_Pesto_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Banana/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Banana/Drop")]
		StudentLevel_Ingredients_Banana_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Cheese/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Cheese/Moving")]
		StudentLevel_Ingredients_Cheese_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Cheese/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Cheese/Impact")]
		StudentLevel_Ingredients_Cheese_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Teabox/Impact_Upper
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Teabox/Impact_Upper")]
		StudentLevel_Interactions_Teabox_Impact_Upper,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedTomatoes/DirectionChange
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedTomatoes/DirectionChange")]
		StudentLevel_Ingredients_CannedTomatoes_DirectionChange,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/TapeDeck/Music_Black
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/TapeDeck/Music_Black")]
		StudentLevel_Interactions_TapeDeck_Music_Black,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Basil/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Basil/Drop")]
		StudentLevel_Ingredients_Basil_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/BigMysteryJar/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/BigMysteryJar/Drop")]
		StudentLevel_Ingredients_BigMysteryJar_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Pesto/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Pesto/Pickup")]
		StudentLevel_Ingredients_Pesto_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Cheese/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Cheese/Pickup")]
		StudentLevel_Ingredients_Cheese_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/BigMysteryJar/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/BigMysteryJar/Respawn")]
		StudentLevel_Ingredients_BigMysteryJar_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Jam/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Jam/Impact")]
		StudentLevel_Ingredients_Jam_Impact,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Teabox/Click
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Teabox/Click")]
		StudentLevel_Interactions_Teabox_Click,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Basil/Pickup_FromPlant
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Basil/Pickup_FromPlant")]
		StudentLevel_Ingredients_Basil_Pickup_FromPlant,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Cheese/Pickup_FromPackage
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Cheese/Pickup_FromPackage")]
		StudentLevel_Ingredients_Cheese_Pickup_FromPackage,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Tile/Open
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Tile/Open")]
		StudentLevel_Interactions_Tile_Open,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Pesto/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Pesto/Moving")]
		StudentLevel_Ingredients_Pesto_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/TapeDeck/Music_Orange
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/TapeDeck/Music_Orange")]
		StudentLevel_Interactions_TapeDeck_Music_Orange,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedTomatoes/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedTomatoes/Pickup")]
		StudentLevel_Ingredients_CannedTomatoes_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedTomatoes/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedTomatoes/Respawn")]
		StudentLevel_Ingredients_CannedTomatoes_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/BigMysteryJar/Pickup
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/BigMysteryJar/Pickup")]
		StudentLevel_Ingredients_BigMysteryJar_Pickup,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Basil/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Basil/Respawn")]
		StudentLevel_Ingredients_Basil_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/BigMysteryJar/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/BigMysteryJar/Respawn_Land")]
		StudentLevel_Ingredients_BigMysteryJar_Respawn_Land,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/CannedTomatoes/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/CannedTomatoes/Moving")]
		StudentLevel_Ingredients_CannedTomatoes_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Pesto/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Pesto/Respawn")]
		StudentLevel_Ingredients_Pesto_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Jam/Drop
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Jam/Drop")]
		StudentLevel_Ingredients_Jam_Drop,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/PeanutButter/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/PeanutButter/Moving")]
		StudentLevel_Ingredients_PeanutButter_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Ramen/Respawn
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Ramen/Respawn")]
		StudentLevel_Ingredients_Ramen_Respawn,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Basil/Grow
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Basil/Grow")]
		StudentLevel_Ingredients_Basil_Grow,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Jam/Moving
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Jam/Moving")]
		StudentLevel_Ingredients_Jam_Moving,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Teabox/Impact_Lowest
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Teabox/Impact_Lowest")]
		StudentLevel_Interactions_Teabox_Impact_Lowest,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Banana/Slice
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Banana/Slice")]
		StudentLevel_Ingredients_Banana_Slice,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/TapeDeck/Music_Blue
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/TapeDeck/Music_Blue")]
		StudentLevel_Interactions_TapeDeck_Music_Blue,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Banana/Pickup_FromBowl
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Banana/Pickup_FromBowl")]
		StudentLevel_Ingredients_Banana_Pickup_FromBowl,

		/// <FMODEventPath>
		/// event:/StudentLevel/Ingredients/Pesto/Impact
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Ingredients/Pesto/Impact")]
		StudentLevel_Ingredients_Pesto_Impact,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ambience/MyRoom_Ambience
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ambience/MyRoom_Ambience")]
		MyRoomLevel_Ambience_MyRoom_Ambience,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ambience/CafeLevel_Ambience
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ambience/CafeLevel_Ambience")]
		CafeLevel_Ambience_CafeLevel_Ambience,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/NumberPad
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/NumberPad")]
		CafeLevel_Interactions_Phone_NumberPad,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/CoffeePot/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/CoffeePot/Impact")]
		CafeLevel_Ingredients_CoffeePot_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Panini/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Panini/Impact")]
		CafeLevel_Ingredients_Panini_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/TeamPhoto/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/TeamPhoto/Moving")]
		CafeLevel_Ingredients_TeamPhoto_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Rat/VaseClick
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Rat/VaseClick")]
		CafeLevel_Interactions_Rat_VaseClick,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Book/Drop
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Book/Drop")]
		MyRoomLevel_Ingredients_Book_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Chalk/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Chalk/Drop")]
		CafeLevel_Ingredients_Chalk_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cake/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cake/Moving")]
		CafeLevel_Ingredients_Cake_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/CoffeeBeans/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/CoffeeBeans/Moving")]
		CafeLevel_Ingredients_CoffeeBeans_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugGreen/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugGreen/Moving")]
		CafeLevel_Ingredients_MugGreen_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Dough/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Dough/Moving")]
		CafeLevel_Ingredients_Dough_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cacao/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cacao/Respawn_Land")]
		CafeLevel_Ingredients_Cacao_Respawn_Land,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/TeaBox/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/TeaBox/Respawn")]
		CafeLevel_Ingredients_TeaBox_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Strawberry/Pickup_FromBowl
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Strawberry/Pickup_FromBowl")]
		CafeLevel_Ingredients_Strawberry_Pickup_FromBowl,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Oven/Spin_StoveDials
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Oven/Spin_StoveDials")]
		CafeLevel_Interactions_Oven_Spin_StoveDials,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Jam/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Jam/Respawn")]
		CafeLevel_Ingredients_Jam_Respawn,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Book/Moving
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Book/Moving")]
		MyRoomLevel_Ingredients_Book_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Avocado/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Avocado/Pickup")]
		CafeLevel_Ingredients_Avocado_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Croissaint/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Croissaint/Drop")]
		CafeLevel_Ingredients_Croissaint_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Croissaint/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Croissaint/Respawn_Land")]
		CafeLevel_Ingredients_Croissaint_Respawn_Land,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/TeaBox/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/TeaBox/Pickup")]
		CafeLevel_Ingredients_TeaBox_Pickup,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Pencil/Drop
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Pencil/Drop")]
		MyRoomLevel_Ingredients_Pencil_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cheese/Pickup_FromStash
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cheese/Pickup_FromStash")]
		CafeLevel_Ingredients_Cheese_Pickup_FromStash,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cheese/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cheese/Pickup")]
		CafeLevel_Ingredients_Cheese_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Paper/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Paper/Moving")]
		CafeLevel_Ingredients_Paper_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Coin/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Coin/Pickup")]
		CafeLevel_Ingredients_Coin_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/ChocoCake/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/ChocoCake/Impact")]
		CafeLevel_Ingredients_ChocoCake_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/CoffeeBeans/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/CoffeeBeans/Respawn_Land")]
		CafeLevel_Ingredients_CoffeeBeans_Respawn_Land,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/CookieJarLid/Impact
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/CookieJarLid/Impact")]
		MyRoomLevel_Ingredients_CookieJarLid_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/CoffeeBeans/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/CoffeeBeans/Impact")]
		CafeLevel_Ingredients_CoffeeBeans_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/ChocoCake/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/ChocoCake/Pickup")]
		CafeLevel_Ingredients_ChocoCake_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugGreen/Pickup_FromShelf_Second
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugGreen/Pickup_FromShelf_Second")]
		CafeLevel_Ingredients_MugGreen_Pickup_FromShelf_Second,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/CoffeeBeans/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/CoffeeBeans/Respawn")]
		CafeLevel_Ingredients_CoffeeBeans_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cacao/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cacao/Pickup")]
		CafeLevel_Ingredients_Cacao_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Nutella/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Nutella/Moving")]
		CafeLevel_Ingredients_Nutella_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/CoffeePot/Spilling
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/CoffeePot/Spilling")]
		CafeLevel_Ingredients_CoffeePot_Spilling,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MetalLid/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MetalLid/Impact")]
		CafeLevel_Ingredients_MetalLid_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Safe/Click
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Safe/Click")]
		CafeLevel_Interactions_Safe_Click,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Dough/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Dough/Pickup")]
		CafeLevel_Ingredients_Dough_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Lettuce/Pickup_FromStash
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Lettuce/Pickup_FromStash")]
		CafeLevel_Ingredients_Lettuce_Pickup_FromStash,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cake/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cake/Respawn")]
		CafeLevel_Ingredients_Cake_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Paper/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Paper/Respawn")]
		CafeLevel_Ingredients_Paper_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Bagel/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Bagel/Respawn")]
		CafeLevel_Ingredients_Bagel_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/CoffeePot/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/CoffeePot/Pickup")]
		CafeLevel_Ingredients_CoffeePot_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/PaperCup/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/PaperCup/Impact")]
		CafeLevel_Ingredients_PaperCup_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/TeaBox/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/TeaBox/Respawn_Land")]
		CafeLevel_Ingredients_TeaBox_Respawn_Land,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/Cactus/Click
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/Cactus/Click")]
		MyRoomLevel_Interactions_Cactus_Click,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Nutella/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Nutella/Drop")]
		CafeLevel_Ingredients_Nutella_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MetalLid/Open
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MetalLid/Open")]
		CafeLevel_Ingredients_MetalLid_Open,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Jam/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Jam/Moving")]
		CafeLevel_Ingredients_Jam_Moving,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Pencil/Impact
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Pencil/Impact")]
		MyRoomLevel_Ingredients_Pencil_Impact,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/FramedPhoto/Fall
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/FramedPhoto/Fall")]
		MyRoomLevel_Interactions_FramedPhoto_Fall,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MetalLid/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MetalLid/Pickup")]
		CafeLevel_Ingredients_MetalLid_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Panini/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Panini/Pickup")]
		CafeLevel_Ingredients_Panini_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Lettuce/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Lettuce/Moving")]
		CafeLevel_Ingredients_Lettuce_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/TeamPhoto/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/TeamPhoto/Drop")]
		CafeLevel_Ingredients_TeamPhoto_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cake/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cake/Impact")]
		CafeLevel_Ingredients_Cake_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Nutella/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Nutella/Respawn_Land")]
		CafeLevel_Ingredients_Nutella_Respawn_Land,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Coin/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Coin/Impact")]
		CafeLevel_Ingredients_Coin_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Chalk/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Chalk/Impact")]
		CafeLevel_Ingredients_Chalk_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cacao/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cacao/Respawn")]
		CafeLevel_Ingredients_Cacao_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/StrawberryCake/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/StrawberryCake/Drop")]
		CafeLevel_Ingredients_StrawberryCake_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Strawberry/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Strawberry/Moving")]
		CafeLevel_Ingredients_Strawberry_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Dough/Pickup_FromBowl
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Dough/Pickup_FromBowl")]
		CafeLevel_Ingredients_Dough_Pickup_FromBowl,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Safe/Unlocking
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Safe/Unlocking")]
		CafeLevel_Interactions_Safe_Unlocking,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Post-it/Pickup
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Post-it/Pickup")]
		MyRoomLevel_Ingredients_Post_it_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Strawberry/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Strawberry/Pickup")]
		CafeLevel_Ingredients_Strawberry_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MetalLid/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MetalLid/Respawn")]
		CafeLevel_Ingredients_MetalLid_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Avocado/Pickup_FromStash
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Avocado/Pickup_FromStash")]
		CafeLevel_Ingredients_Avocado_Pickup_FromStash,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugGreen/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugGreen/Respawn")]
		CafeLevel_Ingredients_MugGreen_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/TeamPhoto/Fall
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/TeamPhoto/Fall")]
		CafeLevel_Interactions_TeamPhoto_Fall,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugWhite/Pickup_FromShelf
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugWhite/Pickup_FromShelf")]
		CafeLevel_Ingredients_MugWhite_Pickup_FromShelf,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cheese/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cheese/Impact")]
		CafeLevel_Ingredients_Cheese_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Panini/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Panini/Drop")]
		CafeLevel_Ingredients_Panini_Drop,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/Coaster/Click
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/Coaster/Click")]
		MyRoomLevel_Interactions_Coaster_Click,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/TeamPhoto/Click
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/TeamPhoto/Click")]
		CafeLevel_Interactions_TeamPhoto_Click,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugGreen/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugGreen/Impact")]
		CafeLevel_Ingredients_MugGreen_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugGreen/Pickup_FromShelf_Third
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugGreen/Pickup_FromShelf_Third")]
		CafeLevel_Ingredients_MugGreen_Pickup_FromShelf_Third,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Bagel/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Bagel/Moving")]
		CafeLevel_Ingredients_Bagel_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Avocado/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Avocado/Impact")]
		CafeLevel_Ingredients_Avocado_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Croissaint/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Croissaint/Respawn")]
		CafeLevel_Ingredients_Croissaint_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/PaperCup/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/PaperCup/Moving")]
		CafeLevel_Ingredients_PaperCup_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/CoffeePot/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/CoffeePot/Respawn")]
		CafeLevel_Ingredients_CoffeePot_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/CakeDoor/HitMax
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/CakeDoor/HitMax")]
		CafeLevel_Interactions_CakeDoor_HitMax,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cacao/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cacao/Impact")]
		CafeLevel_Ingredients_Cacao_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Nutella/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Nutella/Respawn")]
		CafeLevel_Ingredients_Nutella_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/CoffeePot/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/CoffeePot/Drop")]
		CafeLevel_Ingredients_CoffeePot_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Bagel/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Bagel/Impact")]
		CafeLevel_Ingredients_Bagel_Impact,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Pencil/Moving
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Pencil/Moving")]
		MyRoomLevel_Ingredients_Pencil_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Croissaint/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Croissaint/Pickup")]
		CafeLevel_Ingredients_Croissaint_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cheese/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cheese/Drop")]
		CafeLevel_Ingredients_Cheese_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Jam/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Jam/Impact")]
		CafeLevel_Ingredients_Jam_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Oven/Oven_Entry_Small
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Oven/Oven_Entry_Small")]
		CafeLevel_Interactions_Oven_Oven_Entry_Small,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/TeamPhoto/Break
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/TeamPhoto/Break")]
		CafeLevel_Interactions_TeamPhoto_Break,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Bagel/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Bagel/Pickup")]
		CafeLevel_Ingredients_Bagel_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Croissaint/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Croissaint/Impact")]
		CafeLevel_Ingredients_Croissaint_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Nutella/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Nutella/Impact")]
		CafeLevel_Ingredients_Nutella_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Dough/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Dough/Impact")]
		CafeLevel_Ingredients_Dough_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Dough/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Dough/Drop")]
		CafeLevel_Ingredients_Dough_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/PaperCup/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/PaperCup/Pickup")]
		CafeLevel_Ingredients_PaperCup_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Jam/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Jam/Respawn_Land")]
		CafeLevel_Ingredients_Jam_Respawn_Land,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Avocado/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Avocado/Drop")]
		CafeLevel_Ingredients_Avocado_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugWhite/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugWhite/Respawn")]
		CafeLevel_Ingredients_MugWhite_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Avocado/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Avocado/Moving")]
		CafeLevel_Ingredients_Avocado_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/CoffeePot/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/CoffeePot/Moving")]
		CafeLevel_Ingredients_CoffeePot_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Lettuce/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Lettuce/Drop")]
		CafeLevel_Ingredients_Lettuce_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Coin/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Coin/Respawn")]
		CafeLevel_Ingredients_Coin_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/StrawberryCake/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/StrawberryCake/Moving")]
		CafeLevel_Ingredients_StrawberryCake_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Chalk/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Chalk/Respawn")]
		CafeLevel_Ingredients_Chalk_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugGreen/Pickup_FromShelf_First
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugGreen/Pickup_FromShelf_First")]
		CafeLevel_Ingredients_MugGreen_Pickup_FromShelf_First,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Jam/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Jam/Pickup")]
		CafeLevel_Ingredients_Jam_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Paper/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Paper/Drop")]
		CafeLevel_Ingredients_Paper_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Safe/Locked
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Safe/Locked")]
		CafeLevel_Interactions_Safe_Locked,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/Posters/ChangeMedium
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/Posters/ChangeMedium")]
		MyRoomLevel_Interactions_Posters_ChangeMedium,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/TeamPhoto/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/TeamPhoto/Respawn_Land")]
		CafeLevel_Ingredients_TeamPhoto_Respawn_Land,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Book/Impact
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Book/Impact")]
		MyRoomLevel_Ingredients_Book_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/TeamPhoto/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/TeamPhoto/Respawn")]
		CafeLevel_Ingredients_TeamPhoto_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Bagel/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Bagel/Drop")]
		CafeLevel_Ingredients_Bagel_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugGreen/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugGreen/Pickup")]
		CafeLevel_Ingredients_MugGreen_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cake/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cake/Pickup")]
		CafeLevel_Ingredients_Cake_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugWhite/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugWhite/Pickup")]
		CafeLevel_Ingredients_MugWhite_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Chalk/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Chalk/Moving")]
		CafeLevel_Ingredients_Chalk_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Croissaint/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Croissaint/Moving")]
		CafeLevel_Ingredients_Croissaint_Moving,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Book/Pickup
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Book/Pickup")]
		MyRoomLevel_Ingredients_Book_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Calling
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Calling")]
		CafeLevel_Interactions_Phone_Calling,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Safe/Close
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Safe/Close")]
		CafeLevel_Interactions_Safe_Close,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Nutella/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Nutella/Pickup")]
		CafeLevel_Ingredients_Nutella_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Strawberry/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Strawberry/Drop")]
		CafeLevel_Ingredients_Strawberry_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Oven/Oven_Entry_Medium
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Oven/Oven_Entry_Medium")]
		CafeLevel_Interactions_Oven_Oven_Entry_Medium,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Strawberry/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Strawberry/Impact")]
		CafeLevel_Ingredients_Strawberry_Impact,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/CookieJarLid/Pickup
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/CookieJarLid/Pickup")]
		MyRoomLevel_Ingredients_CookieJarLid_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Chalk/Drawing
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Chalk/Drawing")]
		CafeLevel_Ingredients_Chalk_Drawing,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugWhite/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugWhite/Drop")]
		CafeLevel_Ingredients_MugWhite_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/ChocoCake/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/ChocoCake/Drop")]
		CafeLevel_Ingredients_ChocoCake_Drop,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/CookieJarLid/Moving
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/CookieJarLid/Moving")]
		MyRoomLevel_Ingredients_CookieJarLid_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Oven/Oven_Entry_Big
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Oven/Oven_Entry_Big")]
		CafeLevel_Interactions_Oven_Oven_Entry_Big,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Pencil/Respawn
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Pencil/Respawn")]
		MyRoomLevel_Ingredients_Pencil_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/TeaBox/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/TeaBox/Moving")]
		CafeLevel_Ingredients_TeaBox_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cacao/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cacao/Drop")]
		CafeLevel_Ingredients_Cacao_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/StrawberryCake/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/StrawberryCake/Impact")]
		CafeLevel_Ingredients_StrawberryCake_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Panini/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Panini/Respawn")]
		CafeLevel_Ingredients_Panini_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/PaperCup/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/PaperCup/Drop")]
		CafeLevel_Ingredients_PaperCup_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cake/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cake/Drop")]
		CafeLevel_Ingredients_Cake_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Paper/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Paper/Impact")]
		CafeLevel_Ingredients_Paper_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugWhite/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugWhite/Moving")]
		CafeLevel_Ingredients_MugWhite_Moving,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Post-it/Moving
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Post-it/Moving")]
		MyRoomLevel_Ingredients_Post_it_Moving,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Pencil/Pickup
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Pencil/Pickup")]
		MyRoomLevel_Ingredients_Pencil_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/CakeDoor/Slide
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/CakeDoor/Slide")]
		CafeLevel_Interactions_CakeDoor_Slide,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Lettuce/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Lettuce/Impact")]
		CafeLevel_Ingredients_Lettuce_Impact,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/Mug/Lower
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/Mug/Lower")]
		MyRoomLevel_Interactions_Mug_Lower,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/Mug/Upper
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/Mug/Upper")]
		MyRoomLevel_Interactions_Mug_Upper,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/FramedPhoto/Click
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/FramedPhoto/Click")]
		MyRoomLevel_Interactions_FramedPhoto_Click,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/LadyPictureFrame/Click
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/LadyPictureFrame/Click")]
		CafeLevel_Interactions_LadyPictureFrame_Click,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/CookieJarLid/Drop
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/CookieJarLid/Drop")]
		MyRoomLevel_Ingredients_CookieJarLid_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/ChocoCake/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/ChocoCake/Respawn")]
		CafeLevel_Ingredients_ChocoCake_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/ChocoCake/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/ChocoCake/Moving")]
		CafeLevel_Ingredients_ChocoCake_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Oven/Cooking
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Oven/Cooking")]
		CafeLevel_Interactions_Oven_Cooking,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Safe/Open
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Safe/Open")]
		CafeLevel_Interactions_Safe_Open,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MetalLid/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MetalLid/Moving")]
		CafeLevel_Ingredients_MetalLid_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Panini/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Panini/Moving")]
		CafeLevel_Ingredients_Panini_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/LadyPictureFrame/Blink
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/LadyPictureFrame/Blink")]
		CafeLevel_Interactions_LadyPictureFrame_Blink,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugWhite/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugWhite/Impact")]
		CafeLevel_Ingredients_MugWhite_Impact,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Post-it/Release
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Post-it/Release")]
		MyRoomLevel_Ingredients_Post_it_Release,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Jam/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Jam/Drop")]
		CafeLevel_Ingredients_Jam_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cacao/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cacao/Moving")]
		CafeLevel_Ingredients_Cacao_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/CoffeeBeans/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/CoffeeBeans/Pickup")]
		CafeLevel_Ingredients_CoffeeBeans_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Lettuce/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Lettuce/Pickup")]
		CafeLevel_Ingredients_Lettuce_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/StrawberryCake/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/StrawberryCake/Respawn")]
		CafeLevel_Ingredients_StrawberryCake_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/TeamPhoto/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/TeamPhoto/Pickup")]
		CafeLevel_Ingredients_TeamPhoto_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Coin/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Coin/Drop")]
		CafeLevel_Ingredients_Coin_Drop,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/Posters/ChangeLarge
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/Posters/ChangeLarge")]
		MyRoomLevel_Interactions_Posters_ChangeLarge,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Cheese/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Cheese/Moving")]
		CafeLevel_Ingredients_Cheese_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MugGreen/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MugGreen/Drop")]
		CafeLevel_Ingredients_MugGreen_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/TeaBox/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/TeaBox/Impact")]
		CafeLevel_Ingredients_TeaBox_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/RefillIngredients
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/RefillIngredients")]
		CafeLevel_Interactions_Phone_RefillIngredients,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Bagel/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Bagel/Respawn_Land")]
		CafeLevel_Ingredients_Bagel_Respawn_Land,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Oven/Closing
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Oven/Closing")]
		CafeLevel_Interactions_Oven_Closing,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Coin/Pickup_FromJar
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Coin/Pickup_FromJar")]
		CafeLevel_Ingredients_Coin_Pickup_FromJar,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Coin/Moving
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Coin/Moving")]
		CafeLevel_Ingredients_Coin_Moving,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Panini/Respawn_Land
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Panini/Respawn_Land")]
		CafeLevel_Ingredients_Panini_Respawn_Land,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/MetalLid/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/MetalLid/Drop")]
		CafeLevel_Ingredients_MetalLid_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/TeamPhoto/Impact
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/TeamPhoto/Impact")]
		CafeLevel_Ingredients_TeamPhoto_Impact,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/TeaBox/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/TeaBox/Drop")]
		CafeLevel_Ingredients_TeaBox_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/StrawberryCake/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/StrawberryCake/Pickup")]
		CafeLevel_Ingredients_StrawberryCake_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/CoffeeBeans/Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/CoffeeBeans/Drop")]
		CafeLevel_Ingredients_CoffeeBeans_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Chalk/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Chalk/Pickup")]
		CafeLevel_Ingredients_Chalk_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/PaperCup/Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/PaperCup/Respawn")]
		CafeLevel_Ingredients_PaperCup_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Click
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Click")]
		CafeLevel_Interactions_Phone_Click,

		/// <FMODEventPath>
		/// event:/CafeLevel/Ingredients/Paper/Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Ingredients/Paper/Pickup")]
		CafeLevel_Ingredients_Paper_Pickup,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/Posters/ChangeSmall
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/Posters/ChangeSmall")]
		MyRoomLevel_Interactions_Posters_ChangeSmall,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/ChefsBook/Open
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/ChefsBook/Open")]
		MyRoomLevel_Interactions_ChefsBook_Open,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/MovingBox/Remove
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/MovingBox/Remove")]
		MyRoomLevel_Interactions_MovingBox_Remove,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/NumberPad_03
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/NumberPad_03")]
		CafeLevel_Interactions_Phone_NumberPad_03,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/NumberPad_09
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/NumberPad_09")]
		CafeLevel_Interactions_Phone_NumberPad_09,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/NumberPad_Back
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/NumberPad_Back")]
		CafeLevel_Interactions_Phone_NumberPad_Back,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/NumberPad_02
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/NumberPad_02")]
		CafeLevel_Interactions_Phone_NumberPad_02,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/NumberPad_07
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/NumberPad_07")]
		CafeLevel_Interactions_Phone_NumberPad_07,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/NumberPad_04
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/NumberPad_04")]
		CafeLevel_Interactions_Phone_NumberPad_04,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/NumberPad_05
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/NumberPad_05")]
		CafeLevel_Interactions_Phone_NumberPad_05,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/NumberPad_Call
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/NumberPad_Call")]
		CafeLevel_Interactions_Phone_NumberPad_Call,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/NumberPad_06
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/NumberPad_06")]
		CafeLevel_Interactions_Phone_NumberPad_06,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/NumberPad_08
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/NumberPad_08")]
		CafeLevel_Interactions_Phone_NumberPad_08,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/NumberPad_01
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/NumberPad_01")]
		CafeLevel_Interactions_Phone_NumberPad_01,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/ChefsBook/Close
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/ChefsBook/Close")]
		MyRoomLevel_Interactions_ChefsBook_Close,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/MovingBox/Rattle
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/MovingBox/Rattle")]
		MyRoomLevel_Interactions_MovingBox_Rattle,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/ChefsBook/Respawn
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/ChefsBook/Respawn")]
		MyRoomLevel_Interactions_ChefsBook_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/FireAlarm/DePress
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/FireAlarm/DePress")]
		CafeLevel_Interactions_FireAlarm_DePress,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/Plant/Pluck_Leaf
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/Plant/Pluck_Leaf")]
		MyRoomLevel_Interactions_Plant_Pluck_Leaf,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/ShelfPhoto/Click
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/ShelfPhoto/Click")]
		MyRoomLevel_Interactions_ShelfPhoto_Click,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/Box/Close
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/Box/Close")]
		MyRoomLevel_Interactions_Box_Close,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/FireAlarm/Damage
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/FireAlarm/Damage")]
		CafeLevel_Interactions_FireAlarm_Damage,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/PencilHolder/Click
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/PencilHolder/Click")]
		MyRoomLevel_Interactions_PencilHolder_Click,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/CandyBag/Drop
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/CandyBag/Drop")]
		MyRoomLevel_Ingredients_CandyBag_Drop,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/CandyBag/Pickup
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/CandyBag/Pickup")]
		MyRoomLevel_Ingredients_CandyBag_Pickup,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Post-it/RespawnPile
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Post-it/RespawnPile")]
		MyRoomLevel_Ingredients_Post_it_RespawnPile,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/Post-it/Stick
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/Post-it/Stick")]
		MyRoomLevel_Ingredients_Post_it_Stick,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/ShelfPhoto/Respawn
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/ShelfPhoto/Respawn")]
		MyRoomLevel_Interactions_ShelfPhoto_Respawn,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/CandyBag/Moving
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/CandyBag/Moving")]
		MyRoomLevel_Ingredients_CandyBag_Moving,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/CandyBag/Impact
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/CandyBag/Impact")]
		MyRoomLevel_Ingredients_CandyBag_Impact,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/Box/Open
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/Box/Open")]
		MyRoomLevel_Interactions_Box_Open,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/FlowerPot/Respawn
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/FlowerPot/Respawn")]
		MyRoomLevel_Interactions_FlowerPot_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/FireAlarm/Press
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/FireAlarm/Press")]
		CafeLevel_Interactions_FireAlarm_Press,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Ingredients/CandyBag/Respawn
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Ingredients/CandyBag/Respawn")]
		MyRoomLevel_Ingredients_CandyBag_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/FireAlarm/Break
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/FireAlarm/Break")]
		CafeLevel_Interactions_FireAlarm_Break,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/FlowerPot/Click
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/FlowerPot/Click")]
		MyRoomLevel_Interactions_FlowerPot_Click,

		/// <FMODEventPath>
		/// event:/MyRoomLevel/Interactions/Cat/Click
		/// </FMODEventPath>
		[InspectorName("MyRoomLevel/Interactions/Cat/Click")]
		MyRoomLevel_Interactions_Cat_Click,

		/// <FMODEventPath>
		/// event:/UI/Achievement/NotificationClose
		/// </FMODEventPath>
		[InspectorName("UI/Achievement/NotificationClose")]
		UI_Achievement_NotificationClose,

		/// <FMODEventPath>
		/// event:/UI/Book/UnHover_Level
		/// </FMODEventPath>
		[InspectorName("UI/Book/UnHover_Level")]
		UI_Book_UnHover_Level,

		/// <FMODEventPath>
		/// event:/UI/Achievement/NotificationOpen
		/// </FMODEventPath>
		[InspectorName("UI/Achievement/NotificationOpen")]
		UI_Achievement_NotificationOpen,

		/// <FMODEventPath>
		/// event:/UI/ToDo/Close
		/// </FMODEventPath>
		[InspectorName("UI/ToDo/Close")]
		UI_ToDo_Close,

		/// <FMODEventPath>
		/// event:/UI/Book/Hover_Level
		/// </FMODEventPath>
		[InspectorName("UI/Book/Hover_Level")]
		UI_Book_Hover_Level,

		/// <FMODEventPath>
		/// event:/UI/ToDo/Open
		/// </FMODEventPath>
		[InspectorName("UI/ToDo/Open")]
		UI_ToDo_Open,

		/// <FMODEventPath>
		/// event:/UI/ToDo/CrossOut
		/// </FMODEventPath>
		[InspectorName("UI/ToDo/CrossOut")]
		UI_ToDo_CrossOut,

		/// <FMODEventPath>
		/// event:/StudentLevel/Interactions/Letter/ReceiveLetter
		/// </FMODEventPath>
		[InspectorName("StudentLevel/Interactions/Letter/ReceiveLetter")]
		StudentLevel_Interactions_Letter_ReceiveLetter,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Receiver_Drop
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Receiver_Drop")]
		CafeLevel_Interactions_Phone_Receiver_Drop,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Receiver_Pickup
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Receiver_Pickup")]
		CafeLevel_Interactions_Phone_Receiver_Pickup,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Ringing
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Ringing")]
		CafeLevel_Interactions_Phone_Ringing,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/HungUp_Beep
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/HungUp_Beep")]
		CafeLevel_Interactions_Phone_HungUp_Beep,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Call_Police
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Call_Police")]
		CafeLevel_Interactions_Phone_Call_Police,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Receiver_Respawn
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Receiver_Respawn")]
		CafeLevel_Interactions_Phone_Receiver_Respawn,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Receiver_Move
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Receiver_Move")]
		CafeLevel_Interactions_Phone_Receiver_Move,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/PoliceCar
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/PoliceCar")]
		CafeLevel_Interactions_Phone_PoliceCar,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/IngredientDelivery
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/IngredientDelivery")]
		CafeLevel_Interactions_Phone_IngredientDelivery,

		/// <FMODEventPath>
		/// event:/UI/LevelTransition/Fill
		/// </FMODEventPath>
		[InspectorName("UI/LevelTransition/Fill")]
		UI_LevelTransition_Fill,

		/// <FMODEventPath>
		/// event:/UI/Book/Level_Unlock
		/// </FMODEventPath>
		[InspectorName("UI/Book/Level_Unlock")]
		UI_Book_Level_Unlock,

		/// <FMODEventPath>
		/// event:/UI/LevelTransition/Clear
		/// </FMODEventPath>
		[InspectorName("UI/LevelTransition/Clear")]
		UI_LevelTransition_Clear,

		/// <FMODEventPath>
		/// snapshot:/VoidBagel
		/// </FMODEventPath>
		[InspectorName("t:/VoidBagel")]
		VoidBagel,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Call_GoodNumber_01
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Call_GoodNumber_01")]
		CafeLevel_Interactions_Phone_Call_GoodNumber_01,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Call_GoodNumber_02
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Call_GoodNumber_02")]
		CafeLevel_Interactions_Phone_Call_GoodNumber_02,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Call_BadNumber_01
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Call_BadNumber_01")]
		CafeLevel_Interactions_Phone_Call_BadNumber_01,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Call_BadNumber_07
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Call_BadNumber_07")]
		CafeLevel_Interactions_Phone_Call_BadNumber_07,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Call_BadNumber_04
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Call_BadNumber_04")]
		CafeLevel_Interactions_Phone_Call_BadNumber_04,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Call_BadNumber_05
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Call_BadNumber_05")]
		CafeLevel_Interactions_Phone_Call_BadNumber_05,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Call_BadNumber_08
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Call_BadNumber_08")]
		CafeLevel_Interactions_Phone_Call_BadNumber_08,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/VoidBagel/VoidBagel
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/VoidBagel/VoidBagel")]
		CafeLevel_Interactions_VoidBagel_VoidBagel,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Call_BadNumber_06
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Call_BadNumber_06")]
		CafeLevel_Interactions_Phone_Call_BadNumber_06,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Call_BadNumber_03
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Call_BadNumber_03")]
		CafeLevel_Interactions_Phone_Call_BadNumber_03,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Phone/Call_BadNumber_02
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Phone/Call_BadNumber_02")]
		CafeLevel_Interactions_Phone_Call_BadNumber_02,

		/// <FMODEventPath>
		/// event:/CafeLevel/Interactions/Safe/Card_NotAccepted
		/// </FMODEventPath>
		[InspectorName("CafeLevel/Interactions/Safe/Card_NotAccepted")]
		CafeLevel_Interactions_Safe_Card_NotAccepted,

		/// <FMODEventPath>
		/// event:/UI/Feedback/Confetti
		/// </FMODEventPath>
		[InspectorName("UI/Feedback/Confetti")]
		UI_Feedback_Confetti,
	}
}